// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "API服务条款",
        "contact": {
            "name": "霖霖",
            "url": "http://www.swagger.io/support",
            "email": "1589861957@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/createUser": {
            "post": {
                "description": "创建用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "创建用户",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.LinResult"
                        }
                    }
                }
            }
        },
        "/user/test": {
            "get": {
                "description": "swagger测试描述",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "swagger测试标签"
                ],
                "summary": "swagger测试",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.LinResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.LinResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.UserBase": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_port": {
                    "type": "string"
                },
                "device_info": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "lin@qq.com"
                },
                "heartbeat_time": {
                    "type": "integer"
                },
                "identity": {
                    "type": "string"
                },
                "is_logout": {
                    "type": "boolean"
                },
                "login_time": {
                    "type": "integer"
                },
                "logout_time": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "18989190946"
                },
                "username": {
                    "description": "gorm.Model",
                    "type": "string",
                    "example": "lin"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/lin/im/v1",
	Schemes:          []string{},
	Title:            "IM即时通信",
	Description:      "一个go的即时通信项目.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
